language: java
jdk: oraclejdk8
dist: trusty
sudo: true
env:
  global:
    secure: rB4klVqhUBakrp+IAqYZpL2OnFDDz62XUjWRQzzlCdcrHl5p8nuUAk9t6SCFEJh16hLJnol3Ub4bzjYm56tXpHrttXkze3yZb/5NdILL7ro3vfPTHoGmTdwdR3hGvWXrakF0zsz6fsu9I+ex8cLJSIV3RDisNmkF1JknT9+pMsuipKhytlQjsncUfyVCE1rbpeeLV2vDYXWabO/A3uL0gJrQZrSnqhhwxhQ/2riVssQjdUXrqoU3kjO0QzO2i+gsYLFp7spd+/0BwoyKn07FrbnQpmcN1GIkUdCq+7A1RccQ0yG5ymkg09AMmdirlffkdPIroeqwRtjgifYyYxczpXNC4+JeTXmDHLkXigtQRzw75n5ANRTCPvtsg0VxAeDEvI1BCFzCBPF7GQ0rLq599DKSr0a+Eh7pO9nYrmv898WSdrMCynJV1dpG8VLmsHodxcKGIgVWt6vHu7tAnsJaH1fDmAhnHFYYJRqbe4K/llrPTAnMyQLjeWwUiWJQGbmlHQUnauTmQsCLSIGEYD0sFZPFheVxSEhlRb1Uxw8qnREFhTYY/FJplwskun+Lic7EUotQuVSF2taEbO8FiJuLkcVaNU8ANFDaUUmLxPzxyR5g+MRGI3a18kQtGwVMlELJZp7BqSuG45DNeXFaxuHUL7hyxjke2fM8RIizJYDCpaA=
before_deploy:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
deploy:
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh"
    on:
      repo: lapots/judge-rule-engine
      branch: master
